# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NasajcxQ0l-kCHncV6Xz_FQQfQWxa7KJ
"""

#upload a file
from google.colab import files
files.upload()

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

zomato_data=pd.read_csv('/content/zomato.csv',  encoding="latin1")

zomato_data.head()

"""General info"""

#info
zomato_data.info()

#shape
zomato_data.shape

zomato_data.columns

zomato_data.index

zomato_data.describe()

zomato_data['Votes'].count()



#check for null values
zomato_data.isnull().sum()



#graph of null value
sns.heatmap(zomato_data.isnull(),yticklabels=False,cbar=False,cmap='viridis')

country_code_data=pd.read_excel('/content/Country-Code.xlsx')

country_code_data.head()

final_data=pd.merge(zomato_data,country_code_data,on='Country Code', how='left')

final_data.head()

#to check data types
final_data.dtypes

final_data.columns

"""ANALYSIS"""

final_data.Country.value_counts()

country_name=final_data.Country.value_counts().index

country_value=final_data.Country.value_counts().values

##plotting a pie chart
plt.pie(country_value[:3],labels=country_name[:3],autopct='%1.2f%%')

"""We can observe gthat maximum transaction of zomato happens in india followed by usa and uk"""

final_data.columns

final_data.groupby(['Aggregate rating', 'Rating color','Rating text']).size()

rating =final_data.groupby(['Aggregate rating', 'Rating color','Rating text']).size().reset_index().rename(columns={0:'Rating Count'})

#plotting
sns.barplot(x="Aggregate rating", y="Rating Count", data=rating)

